//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountriesApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountriesApp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://restcountries.eu/rest/v2/region/africa.
        /// </summary>
        internal static string AfricaURL {
            get {
                return ResourceManager.GetString("AfricaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://restcountries.eu/rest/v2/region/americas.
        /// </summary>
        internal static string AmericasURL {
            get {
                return ResourceManager.GetString("AmericasURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://restcountries.eu/rest/v2/region/asia.
        /// </summary>
        internal static string AsiaURL {
            get {
                return ResourceManager.GetString("AsiaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password are incorrect or the user doesnt exist. Try again!.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password is empty.
        /// </summary>
        internal static string EmailPasswordEmpty {
            get {
                return ResourceManager.GetString("EmailPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials are not valid please check the email and password.
        /// </summary>
        internal static string Errorhardcoded {
            get {
                return ResourceManager.GetString("Errorhardcoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://restcountries.eu/rest/v2/region/europe.
        /// </summary>
        internal static string EuropeURL {
            get {
                return ResourceManager.GetString("EuropeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jorgehmg17@gmail.com.
        /// </summary>
        internal static string HardCodedEmail {
            get {
                return ResourceManager.GetString("HardCodedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234.
        /// </summary>
        internal static string HardCodedPass {
            get {
                return ResourceManager.GetString("HardCodedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not a valid email please check it.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://restcountries.eu/rest/v2/region/oceania.
        /// </summary>
        internal static string OceaniaURL {
            get {
                return ResourceManager.GetString("OceaniaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkMessage {
            get {
                return ResourceManager.GetString("OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
